-- create database
CREATE DATABASE DRESS_DATA;
USE DRESS_DATA;

-- create table
CREATE TABLE IF NOT EXISTS DRESS (
    `DRESS_ID` VARCHAR(30),	
    `STYLE`	VARCHAR(30),	
    `PRICE`	VARCHAR(30),	
    `RATING` VARCHAR(30),	
    `SIZE` VARCHAR(30),	
    `SEASON` VARCHAR(30),	
    `NECKLINE` VARCHAR(30),	
    `SLEEVELENGTH` VARCHAR(30),		
    `WAISELINE`	VARCHAR(30),	
    `MATERIAL`	VARCHAR(30),	
    `FABRICTYPE` VARCHAR(30),	
    `DECORATION` VARCHAR(30),	
    `PATTERN_TYPE` VARCHAR(30),		
    `RECOMMENDATION` VARCHAR(30)
);

SHOW TABLES;
SELECT * FROM DRESS;

-- load bulk data into the table
LOAD DATA INFILE 
'F:/INEURON_SQL/AttributeDataSet.CSV'
INTO TABLE DRESS 
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
